INSERT INTO `USER` (`ID`,`NAME`,`ADDRESS`,`PHONE_NUMBER`,`ID_NUMBER`)
VALUES (1,'Anuradha', 'Kurunegala', '0716066182','13242552v');

INSERT INTO `LEDGER` (`ID`,`USER_ID`,`CURRENCY`,`AVAILABLE_BALANCE`,`ACCOUNT_NUMBER`)
VALUES (1, 1,'LKR', 100, '02621212');

INSERT INTO `TRANSACTION` (`LEDGER_ID`,`TRANSACTION_DATE`,`TRANSACTION_TYPE`,`AMOUNT`,`DESCRIPTION`)
VALUES (1, NOW(), 'CR', 200, 'First Transaction');